### ISSUE TITLE
Codsworth without voice/conversation delay

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#1] opened 2024-02-14 17:00 UTC
## Describe the bug
After the vault codsworth has no voice/Conversation don't start until i shoot him

### Is it already a known issue?
If so or you are not sure please do not make a new request and see the known issue page. [Here](https://github.com/NomadsReach/Fallout-Anomaly/blob/master/Known%20Issue.md)

### Steps to reproduce
Reloading just before starting the conversation, issue persists

### Environment
 - OS: Windows 10
 - Hardware
 - Other details that you think may affect.

### Additional context
https://youtu.be/dG_YbiWzQbM

**Comment by NomadsReach** [comment] 2024-02-14 19:47
Thank you, being tracked.

**Comment by NomadsReach** [comment] 2024-02-16 18:16
Issue has been fixed in new upcoming patch. Unable to reproduce at this point.

**Closed by NomadsReach** 2024-02-16 18:16 UTC
Labels: bug
