### ISSUE TITLE
AMD Crash Issues

### ISSUE THREAD

**Issue by ZatosTTV** [NomadsReach/Fallout-Anomaly#125] opened 2024-07-31 19:55 UTC
I believe I've reliably fixed the issue with new installs not being able to load past the character creation/special stats assignments without a CTD. (at least for myself) It took me all day and I narrowed it down to a few things, which after fixing, I'm now able to consistently create new characters, load in, and play with without a CTD.

I have an AMD graphics card. I disabled both Weapon Debris Crash Fix (according to crash scanner, this only needs to be enabled for Nvidia cards), and Nvidia reflex support. I then enabled intro tweaks full package. Finally I noticed that MO2 was saying I had a missing master, M1928A1.esp. I went through the download tab, and reinstalled the M1928A1_Thompson. I placed it under weapons on the left pane, and in the load order on the right, I placed it in 21. Weapons - SMG.

After these steps, I am able to play reliably.

**Comment by NomadsReach** [comment] 2024-08-01 22:05
![image](https://github.com/user-attachments/assets/1746b090-66fc-4dfe-8471-27c17b843f09)

**Comment by coc568** [comment] 2024-08-03 16:46
Can't reproduce on my hardware (6800xt) could be an issue with an older amd generation like the 5000 series or a newer one like the 7000 series.

**Comment by NomadsReach** [comment] 2024-08-03 21:10
> > not being able to load past the character creation/special stats assignments without a CTD.
> 
> Can't reproduce on my hardware (6800xt) could be an issue with an older amd generation like the 5000 series or a newer one like the 7000 series.

Right, well those two mods need to be disabled for AMD. - I will look into setting up an AMD profile update as well but going to close this as a one off issue. Will look into the other things.

**Closed** 2024-12-12 07:04 UTC
Labels: bug, unable to reproduce/not an issue.
